# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'commodity',
                'verbose_name_plural': 'commodities',
            },
        ),
        migrations.CreateModel(
            name='Industries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'industry',
                'verbose_name_plural': 'industries',
            },
        ),
        migrations.CreateModel(
            name='Sectors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttpd_admin.Industries')),
            ],
            options={
                'verbose_name': 'sector',
                'verbose_name_plural': 'sectors',
            },
        ),
        migrations.CreateModel(
            name='ISPs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttpd_admin.Sectors')),
            ],
            options={
                'verbose_name': 'isp',
                'verbose_name_plural': 'isps',
            },
        ),
        migrations.CreateModel(
            name='SpecificCommodities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttpd_admin.ISPs')),
            ],
            options={
                'verbose_name': 'special commodity',
                'verbose_name_plural': 'special commodities',
            },
        ),
        migrations.CreateModel(
            name='ProtectionLevels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'protection level',
                'verbose_name_plural': 'protection levels',
            },
        ),
        migrations.CreateModel(
            name='ProtectionTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'protection type',
                'verbose_name_plural': 'protection types',
            },
        ),
        migrations.CreateModel(
            name='TechStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'technology status',
                'verbose_name_plural': 'technology statuses',
            },
        ),
        migrations.CreateModel(
            name='AdopterTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'adopter type',
                'verbose_name_plural': 'adopter types',
            },
        ),    
        migrations.CreateModel(
            name='PotentialAdopters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('adopter_type',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttpd_admin.AdopterTypes')),
            ],
            options={
                'verbose_name': 'potential adopter',
                'verbose_name_plural': 'potential adopters',
            },
        ),
        migrations.CreateModel(
            name='Adopters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=40)),
                ('fax_number', models.CharField(max_length=40)),
                ('email_address', models.EmailField()),
                ('adopter_type',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttpd_admin.AdopterTypes')),
            ],
            options={
                'verbose_name': 'adopters',
                'verbose_name_plural': 'adopters',
            },
        ),
        migrations.CreateModel(
            name='AgencyTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
             ],
            options={
                'verbose_name': 'agency type',
                'verbose_name_plural': 'agency types',
            },
        ),
        migrations.CreateModel(
            name='Agencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=40)),
                ('fax_number', models.CharField(max_length=40)),
                ('agency_type',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttpd_admin.AgencyTypes')),
            ],
            options={
                'verbose_name': 'agency',
                'verbose_name_plural': 'agencies',
            },
        ),
        migrations.CreateModel(
            name='Generators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('availability', models.CharField(choices=[('active', 'Active'), ('retired', 'Retired'), ('deceased', 'Deceased')], default='active', max_length=10)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_generators', to='ttpd_admin.Agencies')),
            ],
            options={
                'verbose_name': 'generator',
                'verbose_name_plural': 'generators',
            },
        ),
    ]
