# Generated by Django 2.0.6 on 2018-08-23 12:57

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('ttpd_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'funding type',
                'verbose_name_plural': 'funding types',
            },
        ),
        migrations.CreateModel(
            name='ProtectionTypeStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'protection status',
                'verbose_name_plural': 'protection statuses',
            },
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.CharField(max_length=80)),
                ('region_roman', models.CharField(max_length=80)),
                ('region_canonical', models.CharField(max_length=160)),
            ],
            options={
                'verbose_name': 'region',
                'verbose_name_plural': 'regions',
            },
        ),
        migrations.CreateModel(
            name='TechCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, limit_choices_to=models.Q(parent=None), null=True, on_delete=django.db.models.deletion.CASCADE, to='ttpd_admin.TechCategories')),
            ],
            options={
                'verbose_name': 'technology category',
                'verbose_name_plural': 'technology categories',
            },
        ),
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.CharField(blank=True, max_length=5, null=True)),
                ('description', models.TextField()),
                ('est_ownership_cost', models.PositiveIntegerField(blank=True, null=True)),
                ('protection_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttpd_admin.ProtectionLevels')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ttpd_admin.Regions')),
            ],
            options={
                'verbose_name': 'technology',
                'verbose_name_plural': 'technologies',
            },
        ),
        migrations.CreateModel(
            name='TechProtectionTypesMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(blank=True, max_length=255)),
                ('meta_serial_number', models.CharField(blank=True, max_length=255)),
                ('date_of_filing', models.DateField(blank=True)),
                ('status', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ttpd_admin.ProtectionTypeStatus')),
            ],
            options={
                'verbose_name': 'technology protection type metadata',
                'verbose_name_plural': 'technology protection type metadatas',
            },
        ),
        migrations.RemoveField(
            model_name='specificcommodities',
            name='parent',
        ),
        migrations.CreateModel(
            name='User',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='adopters',
            options={'verbose_name': 'adopter', 'verbose_name_plural': 'adopters'},
        ),
        migrations.AddField(
            model_name='agencies',
            name='private_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='isps',
            name='specific_commodity',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(parent=None), null=True, on_delete=django.db.models.deletion.CASCADE, to='ttpd_admin.ISPs'),
        ),
        migrations.AlterField(
            model_name='adopters',
            name='fax_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='agencies',
            name='fax_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='generators',
            name='agency',
            field=models.ForeignKey(limit_choices_to={'private_flag': False}, on_delete=django.db.models.deletion.CASCADE, to='ttpd_admin.Agencies'),
        ),
        migrations.AlterField(
            model_name='generators',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='SpecificCommodities',
        ),
    ]
