# Generated by Django 2.0.6 on 2018-08-23 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttpd_admin', '0002_auto_20180823_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnologyCommodities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttpd_admin.Commodities')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttpd_admin.Technologies')),
            ],
            options={
                'verbose_name': 'technology commodity',
                'verbose_name_plural': 'technology commodities',
            },
        ),
        migrations.AddField(
            model_name='technologies',
            name='commodities',
            field=models.ManyToManyField(through='ttpd_admin.TechnologyCommodities', to='ttpd_admin.Commodities'),
        ),
    ]
