# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-13 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttpd_admin', '0002_auto_20180913_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generators',
            name='field_of_expertise',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
