# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-03 03:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttpd_admin', '0003_auto_20180901_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technologyadopters',
            name='break_even_point',
        ),
        migrations.RemoveField(
            model_name='technologyadopters',
            name='expected_returns',
        ),
        migrations.RemoveField(
            model_name='technologyadopters',
            name='financial_analysis',
        ),
        migrations.RemoveField(
            model_name='technologyadopters',
            name='internal_rate_return',
        ),
        migrations.RemoveField(
            model_name='technologyadopters',
            name='investment_cost',
        ),
        migrations.RemoveField(
            model_name='technologyadopters',
            name='net_present_value',
        ),
    ]
