# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-13 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttpd_admin', '0003_auto_20180913_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generators',
            old_name='field_of_expertise',
            new_name='expertise',
        ),
    ]
