# Generated by Django 2.0.6 on 2018-08-23 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttpd_admin', '0003_auto_20180823_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnologyIndustrySectorISPs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_sector_isp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttpd_admin.ISPs')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttpd_admin.Technologies')),
            ],
            options={
                'verbose_name': 'technology isp',
                'verbose_name_plural': 'technology isps',
            },
        ),
        migrations.AddField(
            model_name='technologies',
            name='industry_sector_isp',
            field=models.ManyToManyField(through='ttpd_admin.TechnologyIndustrySectorISPs', to='ttpd_admin.ISPs'),
        ),
    ]
