# Generated by Django 2.0.6 on 2018-08-23 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttpd_admin', '0004_auto_20180823_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnologyCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttpd_admin.TechCategories')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttpd_admin.Technologies')),
            ],
            options={
                'verbose_name': 'technology category',
                'verbose_name_plural': 'technology categories',
            },
        ),
        migrations.AddField(
            model_name='technologies',
            name='categories',
            field=models.ManyToManyField(through='ttpd_admin.TechnologyCategories', to='ttpd_admin.TechCategories'),
        ),
    ]
