# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-15 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttpd_admin', '0004_auto_20180913_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnologyDescriptionTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'technology description type',
                'verbose_name_plural': 'Technology description typs',
            },
        ),
    ]
