# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-04 02:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttpd_admin', '0005_auto_20180904_0947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundings',
            options={'verbose_name': 'technology funding', 'verbose_name_plural': 'technology fundings'},
        ),
        migrations.RenameField(
            model_name='technologies',
            old_name='industry_sector_isp',
            new_name='industry_sector_isps',
        ),
    ]
