# Generated by Django 2.0.6 on 2018-08-23 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttpd_admin', '0006_auto_20180823_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnologyAdopters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adopter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttpd_admin.Adopters')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttpd_admin.Technologies')),
            ],
            options={
                'verbose_name': 'technology adopter',
                'verbose_name_plural': 'technology adopters',
            },
        ),
        migrations.CreateModel(
            name='TechnologyOwners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttpd_admin.Agencies')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttpd_admin.Technologies')),
            ],
            options={
                'verbose_name': 'technology owner',
                'verbose_name_plural': 'technology owners',
            },
        ),
        migrations.AddField(
            model_name='technologies',
            name='adopters',
            field=models.ManyToManyField(blank=True, through='ttpd_admin.TechnologyAdopters', to='ttpd_admin.Adopters'),
        ),
        migrations.AddField(
            model_name='technologies',
            name='owners',
            field=models.ManyToManyField(blank=True, through='ttpd_admin.TechnologyOwners', to='ttpd_admin.Agencies'),
        ),
    ]
