# Generated by Django 2.0.6 on 2018-08-23 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttpd_admin', '0007_auto_20180823_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnologyPotentialAdopters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potential_adopter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttpd_admin.PotentialAdopters')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttpd_admin.Technologies')),
            ],
            options={
                'verbose_name': 'technology potential adopter',
                'verbose_name_plural': 'technology potential adopters',
            },
        ),
        migrations.CreateModel(
            name='TechnologyProtectionTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protection_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttpd_admin.ProtectionTypes')),
                ('protection_type_meta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ttpd_admin.TechProtectionTypesMetadata')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttpd_admin.Technologies')),
            ],
            options={
                'verbose_name': 'technology protection type',
                'verbose_name_plural': 'technology protection types',
            },
        ),
        migrations.CreateModel(
            name='TechnologyStatuses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_complied', models.CharField(blank=True, max_length=5)),
                ('tech_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttpd_admin.TechStatus')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttpd_admin.Technologies')),
            ],
            options={
                'verbose_name': 'technology status',
                'verbose_name_plural': 'technology statuses',
            },
        ),
        migrations.AddField(
            model_name='technologies',
            name='potential_adopters',
            field=models.ManyToManyField(blank=True, through='ttpd_admin.TechnologyPotentialAdopters', to='ttpd_admin.PotentialAdopters'),
        ),
        migrations.AddField(
            model_name='technologies',
            name='protection_types',
            field=models.ManyToManyField(blank=True, through='ttpd_admin.TechnologyProtectionTypes', to='ttpd_admin.ProtectionTypes'),
        ),
        migrations.AddField(
            model_name='technologies',
            name='statuses',
            field=models.ManyToManyField(blank=True, through='ttpd_admin.TechnologyStatuses', to='ttpd_admin.TechStatus'),
        ),
    ]
