# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-21 03:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttpd_admin', '0007_auto_20180915_0831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technologyfulldescriptiontypes',
            options={'verbose_name': 'technology description type', 'verbose_name_plural': 'Technology description types'},
        ),
    ]
