# Generated by Django 2.0.6 on 2018-08-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttpd_admin', '0008_auto_20180823_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fundings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_amount', models.PositiveIntegerField(blank=True)),
                ('duration_start', models.DateField(blank=True)),
                ('duration_end', models.DateField(blank=True)),
                ('properties', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'technology funding',
                'verbose_name_plural': 'technology fundings',
            },
        ),
    ]
