# Generated by Django 2.0.6 on 2018-08-27 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttpd_admin', '0009_fundings'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingImplementors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'technology funding implementor',
                'verbose_name_plural': 'technology funding implementors',
            },
        ),
        migrations.RemoveField(
            model_name='regions',
            name='slug',
        ),
        migrations.AddField(
            model_name='fundings',
            name='donor',
            field=models.ForeignKey(blank=True, default=123, on_delete=django.db.models.deletion.CASCADE, related_name='fundings', to='ttpd_admin.Agencies'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fundings',
            name='funding_type',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='ttpd_admin.FundingTypes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fundings',
            name='technology',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='fundings', to='ttpd_admin.Technologies'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fundingimplementors',
            name='funding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttpd_admin.Fundings'),
        ),
        migrations.AddField(
            model_name='fundingimplementors',
            name='implementor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttpd_admin.Agencies'),
        ),
        migrations.AddField(
            model_name='fundings',
            name='implementing_agencies',
            field=models.ManyToManyField(blank=True, related_name='funding_implementations', through='ttpd_admin.FundingImplementors', to='ttpd_admin.Agencies'),
        ),
    ]
